on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.PROJECT_GITHUB_TOKEN  }}
          projectToken: ${{ secrets.TOKEN_CHROMATIC }}
    env:
      CI: true
